config/routes.rb
TrailProject::Application.routes.draw do

  devise_for :users do
	root :to => 'products#home'
	get 'logout' => 'devise/sessions#destroy'

	match "addproduct" => "admin#addproduct", as: :addproduct
	match "productlist" => "admin#index", as: :productindex
	match "active/:id" => "admin#active", as: :active
	match "deactive/:id" => "admin#deactive", as: :deactive
	match "delete/:id" => "admin#delete", as: :delete
	match "create" => "admin#addrecord"
  end
	root :to => 'products#home'
	match "home" => "products#home", as: :home 
	match "phoneapp" => "products#phoneapp", as: :phoneapp
	match "toolpp" => "products#toolpp", as: :toolpp
	match "winapp" => "products#winapp", as: :winapp
	
	match "accesoriapp" => "products#accesoriapp", as: :accesoriapp
	
	match "addcart/:id" => "products#addcart", as: :addcart
	match "cartdelete/:id" => "products#cartdelete", as: :cartdelete
	match "makepayment" => "products#makepayment", as: :makepayment
	match "complete" => "products#complete", as: :complete
	match "confirm" => "products#confirm", as: :confirm
	match "index" => "products#index", as: :index

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
		user ||= User.new
		if user.has_role? :admin
		  can :manage, :all
		end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :productId, :productName, :productPrice, :quantity, :sessionId
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :isactive, :name, :price, :ptype, :image
  has_attached_file :image
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def addproduct
		@product = Product.new
	end	
	
	def addrecord
		@product = Product.new(params[:product])
      if @product.save
			@product = Product.all
			render :action => 'index'
		else
			render :action => 'failure'
		end
	end
	
	def index
		@product = Product.all
		respond_to do |format|
		  format.html # home.html.erb
		  format.json { render json: @product }
		end
	end
	
	def active
		product = Product.find(params[:id])
				if product.isactive?
				else
					product.isactive=true
				end	
		product.save
		@product = Product.all
		render :action => 'index'
	end
	
	def delete
		product = Product.find(params[:id])
			product.destroy
			@product = Product.all
		render :action => 'index'
	end
	
	def deactive
		product = Product.find(params[:id])
			if product.isactive?
			 product.isactive=false
			end
		product.save
		@product = Product.all
		render :action => 'index'
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
	def home
	end
	
	def index

		reset_session
		$sum=0
		@product = Product.all
		@cartinfo=Cart.where(:sessionId => session[:session_id]).all
   end 
   
   def accesoriapp
		@product = Product.where(:ptype => 'Accesories').all
		@cartinfo=Cart.where(:sessionId => session[:session_id]).all
		respond_to do |format|
		  format.html { render action: "index" }
		end
   end
   
   def toolpp
		@product = Product.where(:ptype => 'Tools').all
		@cartinfo=Cart.where(:sessionId => session[:session_id]).all
		respond_to do |format|
		  format.html { render action: "index" }
		end
   end
   
   def winapp
		@product = Product.where(:ptype => 'WindowsApp').all
		@cartinfo=Cart.where(:sessionId => session[:session_id]).all
		respond_to do |format|
		  format.html { render action: "index" }
		end
   end
   def phoneapp
		@product = Product.where(:ptype => 'PhoneApp').all
		@cartinfo=Cart.where(:sessionId => session[:session_id]).all
		respond_to do |format|
		  format.html { render action: "index" }
		end
   end
   
   def addcart
		@pid=(params[:id])
		@p_price=Product.find(@pid)
		@price=0
			@temp_cart=Cart.find(:first, :conditions => { :sessionId => session[:session_id], :productId => @pid }) 
			if @temp_cart
				@temp_cart.update_attributes(:quantity => (@temp_cart.quantity != 0) ?  @temp_cart.quantity += 1 : 1)
				@price= @temp_cart.productPrice+@p_price.price
				@temp_cart.update_attributes(:productPrice =>@price)
			else
				product = Product.find(params[:id])
				@cart = Cart.create(:sessionId =>  session[:session_id], :quantity =>  1, :productId => @pid, :productName => product.name, :productPrice => product.price)
				@cart.save
			end
			
		@product = Product.all
		@cartinfo=Cart.where(:sessionId => session[:session_id]).all
		
		for cart in @cartinfo
			$sum += cart.productPrice
		end
		respond_to do |format|
		  format.html { render action: "index" }
		end
   end
   
   
   def cartdelete
		cartinfo=Cart.find(params[:id])
		$sum -= cartinfo.productPrice
		cartinfo.destroy
		@cartinfo=Cart.where(:sessionId => session[:session_id]).all
		@product = Product.all
		respond_to do |format|
		  format.html { render action: "index" }
		end
   end 
   
   def makepayment
   $amount = $sum
   $amount = $amount*54
    ActiveMerchant::Billing::Base.mode = :test
    setup_response = gateway.setup_purchase($amount,
		:ip                => request.remote_ip,
		:return_url        => url_for(:action => 'confirm', :only_path => false),
		:cancel_return_url => url_for(:action => 'index', :only_path => false)
		)
		redirect_to gateway.redirect_url_for(setup_response.token)
  end

  def confirm
    redirect_to :action => 'failure' unless params[:token]
    details_response = gateway.details_for(params[:token])
    if !details_response.success?
      @message = details_response.message
      render :action => 'invalid'
      return
    end

    @address = details_response.address
  end

  def complete
 
    purchase = gateway.purchase($amount,
      :ip       => request.remote_ip,
      :payer_id => params[:payer_id],
      :token    => params[:token]
    )
    if !purchase.success?
      @message = purchase.message
      render :action => 'invalid'
      return
    else
      render :action => 'success'
    end
  end


  def gateway
  @gateway ||= ActiveMerchant::Billing::PaypalExpressGateway.new(
    :login    => "sencha_1337868048_biz_api1.yahoo.com",
			:password => "1337868090",
			:signature => "Aejy.wTjg4ea0KV.hYXfwe0krup6AhbEBAGV.wtS-5HDqDLZFxj.dsyp "
  )
  end
   
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/addproduct.html.erb
<br/>
<br/>
<%= form_for(@product, :url => { :action =>'addrecord'}, :html => { :multipart => true} ) do |f| %>
<center>
  <table cellspacing=3px style="margin-left:50px">
	<br/>
	<tr>
		<td><b>Name of Product</b></td>
		<td><%= f.text_field :name %></td>
	</tr>
	<tr>
		<td><b>Product Type</b></td>
		<td><%= f.select :ptype, ["PhoneApp","WindowsApp","Tools","Accesories"] %></td>
	<tr>
	<tr>
		<td><b>Product Description</b></td>
		<td><%= f.text_field :description %></td>
	</tr>
	<tr>
		<td><b>Product Price</b></td>
		<td><%= f.text_field :price %></td>
	<tr>
	<tr>
		<td><b>Is Active</b></td>
		<td><%= f.check_box :isactive %></td>
	</tr>
	<tr>
		<td><b>Product Image</b></td>
		<td><%= f.file_field :image %></td>
	<tr>
</table><br/>
<center><%= f.submit 'Add Product'%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" /></center>

</center>
<% end %>

app/views/admin/delete.html.erb
TEST

app/views/admin/failure.html.erb
product unable to add in to database

app/views/admin/index.html.erb
<br/><br/>
<center>

<table class="list_table" style="border-style:solid;border-width:0px;">
	<tr>
		<th class="list_th">Type</th>
		<th class="list_th">Name</th>
		<th class="list_th">Price</th>
		<th class="list_th">Description</th>
		<th class="list_th">IsActive</th>
		<th class="list_th">Operation</th>
	</tr>
	<%for prod in @product%>
	<tr>
		<td class="list_td"><%= prod.ptype %></td>
		<td class="list_td"><%= prod.name %></td>
		<td class="list_td"><%= prod.price %></td>
		<td class="list_td"><%= prod.description %></td>
		<td class="list_td"><% if prod.isactive? %>
					true
				<%else%>
					false
				<%end%>
		</td>
		<td class="list_td"><b><%= link_to 'Active', active_path(:id =>prod.id) %>|<%= link_to 'DeActive',deactive_path(:id =>prod.id) %>|<%= link_to 'Delete', delete_path(:id =>prod.id) %></b></td>
	</tr>
	<%end%>
</table>
</center>

app/views/admin/success.html.erb
<br/><br/><br/><br/>
<center><h2>sucessfully product added</h2></center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SyneAppStore</title>
  <%= stylesheet_link_tag "application", :media => "screen" %>
  <%= javascript_include_tag  "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
 <script type="text/javascript">
$(document).ready(function(){
$('[name=anchor]').hover(function(){
var s=$(this).attr('rel');
switch(s)
{
case '1':
$('.oferta_content img').attr("src","../img/new/android-market-logo.png");
$('.oferta_title').text("SYNE ANDROID SDK FOR DEVELOPMENT");
$('.oferta_text').text("Its a boundless supply of entertaintment, security, development.");
break;
case '2':
$('.oferta_content img').attr("src","../img/new/windows.png");
$('.oferta_title').text(" SYNE WINDOWS PHONE APPLICATIONS ");
$('.oferta_text').text("Windows has now reached within your palm.Go for it.");
break;
case '3':
$('.oferta_content img').attr("src","../img/new/blackberry.png");
$('.oferta_title').text("SYNE BLACKBERRY ACCESSORIES");
$('.oferta_text').text("easy, seamless, flexible applications for blackberry operating system.");
break;
case '4':
$('.oferta_content img').attr("src","../img/new/ios-icon.png");
$('.oferta_title').text("SYNE iOS APPLICATIONS");
$('.oferta_text').text("Apple has introduced the iOS for its application with Cloud storage facility.");
break;
case '5':
$('.oferta_content img').attr("src","../img/new/bi_logo.png");
$('.oferta_title').text("SYNE BADA OS APPLICATIONS");
$('.oferta_text').text("BADA OS games, accessories, applications for you.");
break;
}
});

});
</script> 

</head>
<body>
<div id="main_container">
		
	  <div id="header">	  
			<div id="logo">
				<a href="#"><img src="../images/DSM_SimplifiedLogo_FullColor copy.png" alt="" border="0" width="237" height="120" /></a>
			</div>
				<div class="oferte_content">
					  <div class="oferta">
							<div class="oferta_content"> 
								<img src="../img/new/android-market-logo.png" width="94" height="92" alt="" border="0" class="oferta_img" />
								  <div class="oferta_details">
									<div class="oferta_title"> Syne Apps Store</div>
									<div class="oferta_text">Applications made with complete power for exploitation..</div>
								  </div>
							</div>
							<div class="oferta_pagination">
								<a name="anchor" href="#" rel="1">1</a>
								<a name="anchor" href="#" rel="2">2</a>
								<a name="anchor" href="#" rel="3">3</a>
								<a name="anchor" href="#" rel="4">4</a>
								<a name="anchor" href="#" rel="5">5</a>
							</div>
					  </div>
					  <div class="top_divider">
							<img src="../images/header_divider.png" alt="" width="1" height="164" />
					  </div>
			    </div>
	  </div>
   <div id="main_content">
			<div id="menu_tab">
				<div class="left_menu_corner"></div>
						<ul class="menu">
							<li><%= link_to "Home",home_path,{ :class =>"nav1"}%></li>
							<%- if user_signed_in? -%>
								<%- if current_user.has_role? :admin -%>
								  <li class="divider"></li>
								  <li><b><%= link_to "Add Products",addproduct_path,{ :class =>"nav2"}%></b></li>
								  <li class="divider"></li>
								  <li><%= link_to "Product Status",productindex_path,{ :class =>"nav2"}%></li>
								  <li class="divider"></li>
								  <li><%= link_to 'Logout', logout_path,{ :class =>"nav4"}, :method => :delete %></li>
								<%else%>
									<li class="divider"></li>
									<li><%= link_to "Products",index_path,{ :class =>"nav2"}%></li>
									<li class="divider"></li>
									<li><%= link_to 'Logout', logout_path,{ :class =>"nav4"}, :method => :delete %></li>
								<%end%>
							<%- else -%>
								  <li class="divider"></li>
							      <li><%= link_to "Products",index_path,{ :class =>"nav2"}%></li>
								  <li class="divider"></li>
								  <li><%= link_to 'Sign in', new_user_session_path,{ :class =>"nav4"} %></li>
							<%- end -%>
						</ul>
				<div class="right_menu_corner"></div>
			</div>
	</div>

<%= yield %>

<br/><br/><br/>

</div>
</body>
</html>

app/views/products/confirm.html.erb
<br/>
<center>
	<h1>Please Confirm Shiping Address</h1>
		<table cellspacing=5px>
		  <tr><td>Name</td><td><b><%= @address['name'] %></b></td></tr>
		  <tr><td>Company</td><td><b><%= @address['company'] %></b></td></tr>
		  <tr><td>Address 1</td><td><b><%= @address['address1'] %></b></td></tr>
		  <tr><td>Address 2</td><td><b><%= @address['address2'] %></b></td></tr>
		  <tr><td>City</td><td><b><%= @address['city'] %></td></b></tr>
		  <tr><td>State</td><td><b><%= @address['state'] %></td></b></tr>
		  <tr><td>Country Code</td><td><b><%= @address['country'] %></b></td></tr>
		  <tr><td>Zip</td><td><b><%= @address['zip'] %></b></td></tr>
		</table>
		<%= form_tag complete_path(:token => params[:token], :payer_id => params[:PayerID]) do %>
		  <%= submit_tag 'Complete Payment' %>
		<% end %>
</center>

app/views/products/home.html.erb
<head>
<%= stylesheet_link_tag "sliderman" %>
<%= javascript_include_tag "sliderman.1.3.7" %>

</style>
</head>

<body>
	<div align="center" id="image" style="margin-left:160px">
	
		
			<center>
				<div id="SliderName_3_3" class="SliderName_3_3" >
				<%= image_tag("/images/3/stock_1229.jpg")%>
					<%= image_tag("/images/3/need.png")%>
					<%= image_tag("/images/3/Happy-Running-Man.png") %>
					<%= image_tag("/images/3/android app.jpg")%>
					<%= image_tag("/images/3/0.33376400 1317363308.jpg")%>
					<%= image_tag("/images/3/applications.png")%>
					<%= image_tag("/images/3/facebooklogo.jpg")%>
					<%= image_tag("/images/3/twitter.jpg")%>

					<%= image_tag("/images/3/imagesskype.jpg")%>
				</div>
			</center>	
				<script type="text/javascript">
					demo3Effect1 = {name: 'myEffect31', top: true, move: true, duration: 400};
					demo3Effect2 = {name: 'myEffect32', right: true, move: true, duration: 400};
					demo3Effect3 = {name: 'myEffect33', bottom: true, move: true, duration: 400};
					demo3Effect4 = {name: 'myEffect34', left: true, move: true, duration: 400};
					demo3Effect5 = {name: 'myEffect35', rows: 3, cols: 9, delay: 50, duration: 100, order: 'random', fade: true};
					demo3Effect6 = {name: 'myEffect36', rows: 2, cols: 4, delay: 100, duration: 400, order: 'random', fade: true, chess: true};

					effectsDemo3 = [demo3Effect1,demo3Effect2,demo3Effect3,demo3Effect4,demo3Effect5,demo3Effect6,'blinds'];
					var demoSlider_3 = Sliderman.slider({container: 'SliderName_3_3', width: 890, height:250,effects: effectsDemo3, display: {autoplay: 3000}});
				</script>
		

	</div> 
<body>

app/views/products/invalid.html.erb
<br/><br/><br/><br/><br/><br/><br/><br/><center><h2>Transaction Failure</h2>

</center>

app/views/products/success.html.erb
<br/><br/><br/><br/><br/><br/><br/><br/><center><h2>Transaction Sucessfully Completed<h2></center>